//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressValidation.XAVService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class Errors : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorDetailType[] errorDetailField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorDetail", Order=0)]
        public ErrorDetailType[] ErrorDetail {
            get {
                return this.errorDetailField;
            }
            set {
                this.errorDetailField = value;
                this.RaisePropertyChanged("ErrorDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
                this.RaisePropertyChanged("TransactionReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class ErrorDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private CodeType primaryErrorCodeField;
        
        private string minimumRetrySecondsField;
        
        private LocationType locationField;
        
        private CodeType[] subErrorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("Severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CodeType PrimaryErrorCode {
            get {
                return this.primaryErrorCodeField;
            }
            set {
                this.primaryErrorCodeField = value;
                this.RaisePropertyChanged("PrimaryErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MinimumRetrySeconds {
            get {
                return this.minimumRetrySecondsField;
            }
            set {
                this.minimumRetrySecondsField = value;
                this.RaisePropertyChanged("MinimumRetrySeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public LocationType Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubErrorCode", Order=4)]
        public CodeType[] SubErrorCode {
            get {
                return this.subErrorCodeField;
            }
            set {
                this.subErrorCodeField = value;
                this.RaisePropertyChanged("SubErrorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class CodeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        private string digestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Digest {
            get {
                return this.digestField;
            }
            set {
                this.digestField = value;
                this.RaisePropertyChanged("Digest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class LocationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationElementNameField;
        
        private string xPathOfElementField;
        
        private string originalValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LocationElementName {
            get {
                return this.locationElementNameField;
            }
            set {
                this.locationElementNameField = value;
                this.RaisePropertyChanged("LocationElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string XPathOfElement {
            get {
                return this.xPathOfElementField;
            }
            set {
                this.xPathOfElementField = value;
                this.RaisePropertyChanged("XPathOfElement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OriginalValue {
            get {
                return this.originalValueField;
            }
            set {
                this.originalValueField = value;
                this.RaisePropertyChanged("OriginalValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class CandidateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressClassificationType addressClassificationField;
        
        private AddressKeyFormatType addressKeyFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressClassificationType AddressClassification {
            get {
                return this.addressClassificationField;
            }
            set {
                this.addressClassificationField = value;
                this.RaisePropertyChanged("AddressClassification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AddressKeyFormatType AddressKeyFormat {
            get {
                return this.addressKeyFormatField;
            }
            set {
                this.addressKeyFormatField = value;
                this.RaisePropertyChanged("AddressKeyFormat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class AddressClassificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class AddressKeyFormatType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consigneeNameField;
        
        private string attentionNameField;
        
        private string[] addressLineField;
        
        private string politicalDivision2Field;
        
        private string politicalDivision1Field;
        
        private string postcodePrimaryLowField;
        
        private string postcodeExtendedLowField;
        
        private string regionField;
        
        private string urbanizationField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ConsigneeName {
            get {
                return this.consigneeNameField;
            }
            set {
                this.consigneeNameField = value;
                this.RaisePropertyChanged("ConsigneeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AttentionName {
            get {
                return this.attentionNameField;
            }
            set {
                this.attentionNameField = value;
                this.RaisePropertyChanged("AttentionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressLine", Order=2)]
        public string[] AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
                this.RaisePropertyChanged("AddressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PoliticalDivision2 {
            get {
                return this.politicalDivision2Field;
            }
            set {
                this.politicalDivision2Field = value;
                this.RaisePropertyChanged("PoliticalDivision2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PoliticalDivision1 {
            get {
                return this.politicalDivision1Field;
            }
            set {
                this.politicalDivision1Field = value;
                this.RaisePropertyChanged("PoliticalDivision1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PostcodePrimaryLow {
            get {
                return this.postcodePrimaryLowField;
            }
            set {
                this.postcodePrimaryLowField = value;
                this.RaisePropertyChanged("PostcodePrimaryLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PostcodeExtendedLow {
            get {
                return this.postcodeExtendedLowField;
            }
            set {
                this.postcodeExtendedLowField = value;
                this.RaisePropertyChanged("PostcodeExtendedLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Urbanization {
            get {
                return this.urbanizationField;
            }
            set {
                this.urbanizationField = value;
                this.RaisePropertyChanged("Urbanization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class CodeDescriptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CodeDescriptionType responseStatusField;
        
        private CodeDescriptionType[] alertField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CodeDescriptionType ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("ResponseStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Alert", Order=1)]
        public CodeDescriptionType[] Alert {
            get {
                return this.alertField;
            }
            set {
                this.alertField = value;
                this.RaisePropertyChanged("Alert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
                this.RaisePropertyChanged("TransactionReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class TransactionReferenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerContextField;
        
        private string transactionIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerContext {
            get {
                return this.customerContextField;
            }
            set {
                this.customerContextField = value;
                this.RaisePropertyChanged("CustomerContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionIdentifier {
            get {
                return this.transactionIdentifierField;
            }
            set {
                this.transactionIdentifierField = value;
                this.RaisePropertyChanged("TransactionIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class RequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] requestOptionField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestOption", Order=0)]
        public string[] RequestOption {
            get {
                return this.requestOptionField;
            }
            set {
                this.requestOptionField = value;
                this.RaisePropertyChanged("RequestOption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
                this.RaisePropertyChanged("TransactionReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ups.com/WSDL/XOLTWS/XAV/v1.0", ConfigurationName="XAVService.XAVPortType")]
    public interface XAVPortType {
        
        // CODEGEN: Generating message contract since the operation ProcessXAV is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://onlinetools.ups.com/webservices/XAVBinding/v1.0", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AddressValidation.XAVService.Errors), Action="http://onlinetools.ups.com/webservices/XAVBinding/v1.0", Name="Errors", Namespace="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AddressValidation.XAVService.XAVResponse1 ProcessXAV(AddressValidation.XAVService.XAVRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://onlinetools.ups.com/webservices/XAVBinding/v1.0", ReplyAction="*")]
        System.IAsyncResult BeginProcessXAV(AddressValidation.XAVService.XAVRequest1 request, System.AsyncCallback callback, object asyncState);
        
        AddressValidation.XAVService.XAVResponse1 EndProcessXAV(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UPSSecurityUsernameToken usernameTokenField;
        
        private UPSSecurityServiceAccessToken serviceAccessTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UPSSecurityUsernameToken UsernameToken {
            get {
                return this.usernameTokenField;
            }
            set {
                this.usernameTokenField = value;
                this.RaisePropertyChanged("UsernameToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UPSSecurityServiceAccessToken ServiceAccessToken {
            get {
                return this.serviceAccessTokenField;
            }
            set {
                this.serviceAccessTokenField = value;
                this.RaisePropertyChanged("ServiceAccessToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityUsernameToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityServiceAccessToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessLicenseNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessLicenseNumber {
            get {
                return this.accessLicenseNumberField;
            }
            set {
                this.accessLicenseNumberField = value;
                this.RaisePropertyChanged("AccessLicenseNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class XAVRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestType requestField;
        
        private string regionalRequestIndicatorField;
        
        private string maximumCandidateListSizeField;
        
        private AddressKeyFormatType addressKeyFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0", Order=0)]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("Request");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegionalRequestIndicator {
            get {
                return this.regionalRequestIndicatorField;
            }
            set {
                this.regionalRequestIndicatorField = value;
                this.RaisePropertyChanged("RegionalRequestIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MaximumCandidateListSize {
            get {
                return this.maximumCandidateListSizeField;
            }
            set {
                this.maximumCandidateListSizeField = value;
                this.RaisePropertyChanged("MaximumCandidateListSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AddressKeyFormatType AddressKeyFormat {
            get {
                return this.addressKeyFormatField;
            }
            set {
                this.addressKeyFormatField = value;
                this.RaisePropertyChanged("AddressKeyFormat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class XAVResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseType responseField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private AddressClassificationType addressClassificationField;
        
        private CandidateType[] candidateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0", Order=0)]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AmbiguousAddressIndicator", typeof(string), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("NoCandidatesIndicator", typeof(string), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("ValidAddressIndicator", typeof(string), Order=1)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AddressClassificationType AddressClassification {
            get {
                return this.addressClassificationField;
            }
            set {
                this.addressClassificationField = value;
                this.RaisePropertyChanged("AddressClassification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Candidate", Order=4)]
        public CandidateType[] Candidate {
            get {
                return this.candidateField;
            }
            set {
                this.candidateField = value;
                this.RaisePropertyChanged("Candidate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        AmbiguousAddressIndicator,
        
        /// <remarks/>
        NoCandidatesIndicator,
        
        /// <remarks/>
        ValidAddressIndicator,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XAVRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
        public AddressValidation.XAVService.UPSSecurity UPSSecurity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0", Order=0)]
        public AddressValidation.XAVService.XAVRequest XAVRequest;
        
        public XAVRequest1() {
        }
        
        public XAVRequest1(AddressValidation.XAVService.UPSSecurity UPSSecurity, AddressValidation.XAVService.XAVRequest XAVRequest) {
            this.UPSSecurity = UPSSecurity;
            this.XAVRequest = XAVRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XAVResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0", Order=0)]
        public AddressValidation.XAVService.XAVResponse XAVResponse;
        
        public XAVResponse1() {
        }
        
        public XAVResponse1(AddressValidation.XAVService.XAVResponse XAVResponse) {
            this.XAVResponse = XAVResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XAVPortTypeChannel : AddressValidation.XAVService.XAVPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessXAVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ProcessXAVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AddressValidation.XAVService.XAVResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AddressValidation.XAVService.XAVResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XAVPortTypeClient : System.ServiceModel.ClientBase<AddressValidation.XAVService.XAVPortType>, AddressValidation.XAVService.XAVPortType {
        
        private BeginOperationDelegate onBeginProcessXAVDelegate;
        
        private EndOperationDelegate onEndProcessXAVDelegate;
        
        private System.Threading.SendOrPostCallback onProcessXAVCompletedDelegate;
        
        public XAVPortTypeClient() {
        }
        
        public XAVPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XAVPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XAVPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XAVPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ProcessXAVCompletedEventArgs> ProcessXAVCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddressValidation.XAVService.XAVResponse1 AddressValidation.XAVService.XAVPortType.ProcessXAV(AddressValidation.XAVService.XAVRequest1 request) {
            return base.Channel.ProcessXAV(request);
        }
        
        public AddressValidation.XAVService.XAVResponse ProcessXAV(AddressValidation.XAVService.UPSSecurity UPSSecurity, AddressValidation.XAVService.XAVRequest XAVRequest) {
            AddressValidation.XAVService.XAVRequest1 inValue = new AddressValidation.XAVService.XAVRequest1();
            inValue.UPSSecurity = UPSSecurity;
            inValue.XAVRequest = XAVRequest;
            AddressValidation.XAVService.XAVResponse1 retVal = ((AddressValidation.XAVService.XAVPortType)(this)).ProcessXAV(inValue);
            return retVal.XAVResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AddressValidation.XAVService.XAVPortType.BeginProcessXAV(AddressValidation.XAVService.XAVRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginProcessXAV(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginProcessXAV(AddressValidation.XAVService.UPSSecurity UPSSecurity, AddressValidation.XAVService.XAVRequest XAVRequest, System.AsyncCallback callback, object asyncState) {
            AddressValidation.XAVService.XAVRequest1 inValue = new AddressValidation.XAVService.XAVRequest1();
            inValue.UPSSecurity = UPSSecurity;
            inValue.XAVRequest = XAVRequest;
            return ((AddressValidation.XAVService.XAVPortType)(this)).BeginProcessXAV(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddressValidation.XAVService.XAVResponse1 AddressValidation.XAVService.XAVPortType.EndProcessXAV(System.IAsyncResult result) {
            return base.Channel.EndProcessXAV(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AddressValidation.XAVService.XAVResponse EndProcessXAV(System.IAsyncResult result) {
            AddressValidation.XAVService.XAVResponse1 retVal = ((AddressValidation.XAVService.XAVPortType)(this)).EndProcessXAV(result);
            return retVal.XAVResponse;
        }
        
        private System.IAsyncResult OnBeginProcessXAV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AddressValidation.XAVService.UPSSecurity UPSSecurity = ((AddressValidation.XAVService.UPSSecurity)(inValues[0]));
            AddressValidation.XAVService.XAVRequest XAVRequest = ((AddressValidation.XAVService.XAVRequest)(inValues[1]));
            return this.BeginProcessXAV(UPSSecurity, XAVRequest, callback, asyncState);
        }
        
        private object[] OnEndProcessXAV(System.IAsyncResult result) {
            AddressValidation.XAVService.XAVResponse retVal = this.EndProcessXAV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnProcessXAVCompleted(object state) {
            if ((this.ProcessXAVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ProcessXAVCompleted(this, new ProcessXAVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ProcessXAVAsync(AddressValidation.XAVService.UPSSecurity UPSSecurity, AddressValidation.XAVService.XAVRequest XAVRequest) {
            this.ProcessXAVAsync(UPSSecurity, XAVRequest, null);
        }
        
        public void ProcessXAVAsync(AddressValidation.XAVService.UPSSecurity UPSSecurity, AddressValidation.XAVService.XAVRequest XAVRequest, object userState) {
            if ((this.onBeginProcessXAVDelegate == null)) {
                this.onBeginProcessXAVDelegate = new BeginOperationDelegate(this.OnBeginProcessXAV);
            }
            if ((this.onEndProcessXAVDelegate == null)) {
                this.onEndProcessXAVDelegate = new EndOperationDelegate(this.OnEndProcessXAV);
            }
            if ((this.onProcessXAVCompletedDelegate == null)) {
                this.onProcessXAVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProcessXAVCompleted);
            }
            base.InvokeAsync(this.onBeginProcessXAVDelegate, new object[] {
                        UPSSecurity,
                        XAVRequest}, this.onEndProcessXAVDelegate, this.onProcessXAVCompletedDelegate, userState);
        }
    }
}
